version: '3.8'

services:
  backend:
    build: .
    networks:
      - backend-network

  database:
    image: postgres:15.3
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - db-network

  proxy:
    image: nginx:1.25
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "443:443"
    networks:
      - proxy-network

volumes:
  db_data:

networks:
  backend-network:
  db-network:
  proxy-network:
